### ISSUE TITLE
Substitution sample not working

### ISSUE THREAD

**Issue by stanciuadrian** [asc-community/AngouriMathSite#15]
Code from `research` page:

![image](https://user-images.githubusercontent.com/2334569/133922890-0b054de1-b0ad-4023-8bb0-d98235804daa.png)

Opening `AngouriMath.FSharp.Shortcuts` fixes the sample.

**Comment by WhiteBlackGoose** [comment]
Thanks for the report. You can PR it too (or I will fix soon)
