### ISSUE TITLE
Fix margins between cards

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMathSite#2]
![image](https://user-images.githubusercontent.com/31178401/97753141-57b27900-1b06-11eb-824b-ee821e743038.png)

**Comment by TheSeems** [comment]
![image](https://user-images.githubusercontent.com/38561919/97791739-c535d680-1be6-11eb-999e-a84c18267925.png)
Now there are no cards anymore. Simple as it is.
